### PR TITLE
type is not a keyword but $type

### PR DESCRIPTION
**Pull request by kevinresol**

### CODE REVIEW

**Comment by kevinresol** [comment]
Honestly, I didn't test. Just wanna get rid of the highlight for `type` (because I use that very often as parameter name).

That is weird, I thought the regex syntax is correct (theoretically)

**Comment by kevinresol** [comment]
Ok I know why. Because the regex is prepended by `\b` which match all non-word characters including `$`... let's see if I can fix it

**Comment by kevinresol** [comment]
This should work now

**Comment by theRemix** [comment]
yes this looks good

image

merging and tagging

**Pull request merged**
